name: ci

on:
  schedule:
    # build every tuesday
    - cron: '* * 1 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0' ]
        webserver: [ 'apache', 'nginx' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.webserver }}-${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: pluswerk/php-dev:${{ matrix.webserver }}-${{ matrix.php }},pluswerk/php-dev:${{ matrix.webserver }}-${{ matrix.php }}-${{ steps.date.outputs.date }}
          build-args: FROM=webdevops/php-${{ matrix.webserver }}-dev:${{ matrix.php }}
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build_dev.outputs.digest }}
